### ISSUE TITLE
gcp clourunv2 service does not update with new latest image

### ISSUE THREAD

**Issue by yehudamakarov** [pulumi/pulumi-gcp#1166]
### What happened?

- building an image with pulumi, and then using the output of the `imageName` should always trigger a cloud run service revision if using the `latest` tag
- in a different go project using `v1` I benefit from the expected behavior
- using something like the below code, and passing the `imageName` to the service, it does not trigger further revisions on `pulumi up`

```
const myImage = new docker.Image(names.dockerImage, {
    build: {
      context: "../",
      dockerfile: "../Dockerfile",
      platform: "linux/amd64",
    },
    imageName: pulumi
      .all([artifactRepoLocation, artifactRepoProject, artifactRepoId])
      .apply(
        ([l, p, i]) =>
          `${l}-docker.pkg.dev/${p}/${i}/${names.imageName}:${names.imageTag}`
      ),
    registry: {
      // the empty block because we log in with gcloud
    },
  });
```

```
  const myService = new gcp.cloudrunv2.Service(
    names.cloudRunService,
    {
      ingress: "INGRESS_TRAFFIC_ALL",
      location: location,
      traffics: [
        {
          percent: 100,
          type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST",
        },
      ],
      template: {
        containers: [
          {
            image: myImage.imageName,
            envs: [
              {
                name: "SESSION_SECRET",
                valueSource: {
                  secretKeyRef: {
                    secret: secrets.sessionSecret.name,
                    version: "latest",
                  },
                },
              },
            ],
          },
        ],
      },
    },
    { dependsOn: [myImage] }
  );

```

### Expected Behavior

every time there is a new image there should be a new service revision

### Steps to reproduce

1. pulumi ts
2. make a docker image
3. use its `imageName` with the `latest` tag as the `image` for a clourunv2 service
4. I should get new service revisions with new builds (`latest`)

### Output of `pulumi about`

pulumi about
CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.15.1'

etc.

### Additional context

maybe in go, new strings are always new or new structs etc. so it always looks new, and in TS the strings are compared and `latest` is always that? if so how can I trigger new revisions on every `latest` image?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by yehudamakarov** [comment]
now i'm just realizing for the `go` code, `imageName` includes the sha. for the `typescript` code, `imageName` does **not** include the sha.

**Comment by lukehoban** [comment]
If you are using the v4 docker provider, the `imageName` property will not change when the image is rebuilt. You should use https://www.pulumi.com/registry/packages/docker/api-docs/image/#repodigest_nodejs instead, as that will be unique for each rebuild, and will thus force a change to the cloudrun Service.

**Comment by yehudamakarov** [comment]
I see. 

I just updated my go repo to v4 of the docker provider. And the `imageName` had a new tag on a new build. Yet the typescript version doesn't do the same?

thanks @lukehoban - trying

**Comment by yehudamakarov** [comment]
ok v4 across all languages is not working and I'm looking into repoDigest now

**Comment by yehudamakarov** [comment]
looks like there were some changes in v4 and that meant `imageName` stopped having a sha but you can simply use `repoDigest`. this was true as well for `go`.

**Comment by WaldoJeffers** [comment]
@lukehoban Do you think it would make sense to update the docs with this insight? I faced the same issue and came to the same conclusion (using `repoDigest`) after a lot of time consuming trial & error. Nearly all the Pulumi examples I found suggested using `imageName`.

Also, for some reason, `repoDigest` is typed as `Image.repoDigest: pulumi.Output<string | undefined>` meaning you can't use it directly. You either need to use the non-null assertion operator (`!`), or something like:
```js
{
  image: pulumi
          .all([image.repoDigest, image.imageName])
          .apply(([repoDigest, imageName]) => repoDigest || imageName),
}```

**Comment by guineveresaenger** [comment]
hi @WaldoJeffers - would you be able to link us to the specific examples you'd like updated? I'm adding a note to the provider docs, but would like to follow up with other sources of confusion. 🙏

**Comment by WaldoJeffers** [comment]
Hello @guineveresaenger ,
I'd be happy to!

- [Google Cloud Run: Serverless Containers](https://www.pulumi.com/blog/google-cloud-run-serverless-containers/#deploy-to-cloud-run)
- [This gcp-ts-cloudrun guide](https://github.com/pulumi/examples/blob/master/gcp-ts-cloudrun/index.ts#L62) referenced from [this page](https://www.pulumi.com/registry/packages/gcp/how-to-guides/gcp-ts-cloudrun/)
- [This container-gcp-typescript example](https://github.com/pulumi/templates/blob/master/container-gcp-typescript/index.ts#L64)

There's also this [gcp-ts-docker-gcr-cloudrun example](https://github.com/pulumi/examples/blob/master/gcp-ts-docker-gcr-cloudrun/cloud-run-deploy/index.ts#L47) which was a bit confusing to me, not specifically because of how the image name is retrieved, but because the whole set up seems quite different from the ones mentioned above. In this template, access to a docker registry is done through `new docker.Provider`, whereas in the `container-gcp-typescript`, it's done through `new gcp.artifactregistry.Repository`.

I decided to use the latter, because the former seemed to reference Google Container Registry, which has been deprecated in favour of Artifact Registry.


Overall, I felt like [this blog post](https://www.pulumi.com/blog/google-cloud-run-serverless-containers/#deploy-to-cloud-run) was a good intro as to how to deploy a Cloud Run custom application (minus the `imageName` part), which I would have expected from [the guides section](https://www.pulumi.com/registry/packages/gcp/how-to-guides/gcp-ts-cloudrun/)  or [the templates section](https://www.pulumi.com/templates/container-service/gcp/); rather than finding this in the blog posts section.


Lastly, what was even weirder to me was that `imageName` didn't seem to be referenced in [`docker.Image's outputs`](https://www.pulumi.com/registry/packages/docker/api-docs/image/#outputs) (unless I missed something)


Thanks, let me know if I can further help
