### ISSUE TITLE
BucketObject gets deleted when changing the contents

### ISSUE THREAD

**Issue by Inkdpixels** [pulumi/pulumi-gcp#152]
When updating the contents of a `BucketObject` the provider seems to create the replacement and deleting it alltogether which leads to no object at all. The pulumi state however still reflects that the object exists, leading to a unexpected behavior and weird state to work on.

### Versions:

**pulumi plugin ls**
```
gcp         resource  0.18.4   74 MB  n/a        13 minutes ago
kubernetes  resource  0.23.1   52 MB  n/a        12 minutes ago
random      resource  0.5.2    36 MB  n/a        10 minutes ago
```

**pulumi version**
```
v0.17.10
```

### Example:

```ts
import * as gcp from "@pulumi/gcp";

const myObject = new gcp.storage.BucketObject(
    "my-bucket-object",
    {
      bucket: "my-bucket",
      name: "my-object",
      content: "foo-1"
    }
);


export { myObject };
``` 

Apply the changes, inspect the created object, change the content to e.g. `foo-2` and apply again, the object should be deleted with the following output of pulumi.

```
Updating (my-stack):
    pulumi:pulumi:Stack my-stack running 
 ++ gcp:storage:BucketObject my-bucket-object creating replacement [diff: ~content]
 ++ gcp:storage:BucketObject my-bucket-object created replacement [diff: ~content]
 +- gcp:storage:BucketObject my-bucket-object replacing [diff: ~content]
 +- gcp:storage:BucketObject my-bucket-object replaced [diff: ~content]
 -- gcp:storage:BucketObject my-bucket-object deleting original [diff: ~content]
 -- gcp:storage:BucketObject my-bucket-object deleted original [diff: ~content]
```

### Expected behavior

Pulumi should not delete the replacement.

**Comment by ellismg** [comment]
Guessing that we just need to mark this resource as "deleteBeforeReplace"? @stack72 @jen20?

**Comment by lukehoban** [comment]
Note that this is almost certainly a bug in the upstream Terraform provider. It should error instead of silently adopt. 

Also note that this can be worked around with either of:
1. Not set `name` explicitly so that the bucket gets a unique name
2. Specify `deleteBeforeReplace: true` in user code to ask for the resource to be deleted so the name can be reused

I’m not as much of a fan of forcing the resource to be delete before replace in the provider itself - as that is not necessary (and indeed harmful) when autonaming is applied. 

I think the only action we should take is to ensure the upstream provider is fixed to error instead of silently adopt here.
