### ISSUE TITLE
Set the user agent in requests

### ISSUE THREAD

**Issue by danawillow** [pulumi/pulumi-gcp#156]
In Terraform, we set the user agent [here](https://github.com/terraform-providers/terraform-provider-google/blob/efc0e61a8ea912a4be3b8a7350de6b20aa836c19/google/config.go#L129), which tags GCP requests as coming from Terraform. I haven't dug too deep, but my guess is that the Pulumi requests are probably still sending the Terraform string. Would be great if that could be looked into, and if that is the case, changed to a Pulumi one. Thanks!

**Comment by lukehoban** [comment]
>  haven't dug too deep, but my guess is that the Pulumi requests are probably still sending the Terraform string. 

Yes - this is the case today - and it's something we'd love to fix. Ideally we would augment the user agent, since we want to both credit the fact that it's still the Terraform Google Provider being used, but also annotate that it's the `pulumi` CLI/engine driving the deployments.

> Would be great if that could be looked into, and if that is the case, changed to a Pulumi one. 

We've looked into this in the past, and haven't been able to come with a super clean approach.  With the current provider structure, we would need to maintain a permanent fork with this internal code changed.  We would love to not have to do that.  If these strings (or the key inputs to them) were package level vars that could be overriden with `-ldflags "-X ..."`, we could easily configure.  Or if there were other ways to configure this user agent either at build/link time or at runtime.

**Comment by danawillow** [comment]
Thanks for the quick response, @lukehoban!

Right now, the provider version is overridable via ldflags:
- https://github.com/terraform-providers/terraform-provider-google/blob/master/google/config.go#L127
- https://github.com/terraform-providers/terraform-provider-google/blob/master/version/version.go#L5
- https://github.com/terraform-providers/terraform-provider-google/blob/master/GNUmakefile#L16

The TPG version is derivable from the pulumi version, right? If so, using the pulumi version there would make the full string something like `Terraform/0.12.0 (+https://www.terraform.io) terraform-provider-google/pulumi-0.8.6`, which is maybe more verbose than you'd like but would be something. We could also talk about a PR to TPG that made more portions of the user agent overridable in this way.

**Comment by lblackstone** [comment]
I just checked the current behavior, and it looks like we're setting the user agent like this now:
```
google-api-go-client/0.5 Pulumi/3.0 (GPN:Pulumi; https://www.pulumi.com) pulumi-gcp/v6.45.0,gzip(gfe)
```

This change was made in our fork here: https://github.com/pulumi/terraform-provider-google-beta/commit/419924e41547aff41e2f006e75f3da1d6e05982f
