### ISSUE TITLE
Bucket IAM Binding input docs misaligned

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-gcp#1920]
### What happened?

The input descriptions of the IAM binding resource are wrong - looks like a bunch of docs from the `members` input is in the `bucket` input and the `members` input description is empty.

### Example

https://www.pulumi.com/registry/packages/gcp/api-docs/storage/bucketiambinding/#bucket_yaml

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
I am fairly certain that this happened because the heading for `member` is `member/members` which won't produce a match in docs discovery.
This is probably worth a patch on our end if it's a prominent resource, but not something that should be categorically addressed. I'll push a patch and see if that addresses it.

**Comment by guineveresaenger** [comment]
Same issue for DNS IAM Binding: https://www.pulumi.com/registry/packages/gcp/api-docs/dns/dnsmanagedzoneiambinding/

There's a handful of others. Might be worth making a docs edit rule.
