### ISSUE TITLE
MetricDescriptor object lacks fields that exist in GCP API 

### ISSUE THREAD

**Issue by neluzhin** [pulumi/pulumi-gcp#215]
Pulumi's interface:

```typescript
interface MetricMetricDescriptor {
    labels?: pulumi.Input<pulumi.Input<inputs.logging.MetricMetricDescriptorLabel>[]>;
    metricKind: pulumi.Input<string>;
    valueType: pulumi.Input<string>;
}
```

Actual API: https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics#MetricDescriptor

**Comment by pgavlin** [comment]
Which fields in particular do you need?

**Comment by neluzhin** [comment]
`unit` and `displayName`

**Comment by pgavlin** [comment]
These fields are missing because they are not supported by the upstream Terraform provider. `unit` will be added with the next release (see https://github.com/terraform-providers/terraform-provider-google/issues/3881); we will get support for the same once we pull in those changes.

I couldn't find an issue for `displayName` in the upstream provider, so I filed https://github.com/terraform-providers/terraform-provider-google/issues/4419. We'll use that issue to track adding support for that fields.
