### ISSUE TITLE
gcp.container.getEngineVersions().latestMasterVersion hangs indefinitely

### ISSUE THREAD

**Issue by colinbankier** [pulumi/pulumi-gcp#235]
In attempting to follow the guide at https://www.pulumi.com/docs/tutorials/kubernetes/gke/
I found that pulumi would hang indefinitely during preview with no error on
```
const engineVersion = gcp.container.getEngineVersions().latestMasterVersion;
```
Looking this up manually and supplying the value, and things succeed normally to create the cluster.
Pulumi version v1.3.1, and a fresh project with latest dependencies.

**Comment by clstokes** [comment]
@colinbankier what version of Node are you using? You can find this with `node -v`.

We're currently tracking an issue with Node `v12.11.1` at https://github.com/pulumi/pulumi/issues/3309. If you're on Node `v12.11.1`, you should be able to downgrade to a previous Node 12.x or 10.x version to work around this until that issue is resolved.

If you're not on that version, could you provide your Node version as well as the output of `npm ls`? Thanks.

**Comment by colinbankier** [comment]
Thanks @clstokes - I did indeed have node v12.11.1. I downgraded and things now work, so definitely seems like the same issue.

**Comment by lukehoban** [comment]
Thanks for confirming @colinbankier. Will close this out and continue tracking the core issue in #3309.
