### ISSUE TITLE
Doubled functions: `LookupInstanceGroup()` & `GetInstanceGroup()`

### ISSUE THREAD

**Issue by Dominik-K** [pulumi/pulumi-gcp#330]
There are 2 functions which have the same functionality but different API:

* [`compute.GetInstanceGroup()` at `instanceGroup.go`](https://github.com/pulumi/pulumi-gcp/blob/master/sdk/go/gcp/compute/instanceGroup.go#L90-L98)
* and [`compute.LookupInstanceGroup()` at `getInstanceGroup.go`](https://github.com/pulumi/pulumi-gcp/blob/master/sdk/go/gcp/compute/getInstanceGroup.go#L10-L41)

The `LookupInstanceGroup()` has broader range with the `LookupInstanceGroupArgs` and is better documented. Anyway, confusing filenames.

Related: https://github.com/pulumi/docs/issues/3075

**Comment by Dominik-K** [comment]
@leezen The related issue doesn't solve this here.

I think it's still a bug that the `compute.GetInstanceGroup()` exists. The `compute.LookupInstanceGroup()` should be the only function:

1. Concise with the renaming-schema ([avoid naming collisions](https://github.com/pulumi/docs/issues/3276)) and
2. The `LookupInstanceGroup()` includes all functionality of the `GetInstanceGroup()`, AFAICS.

**Comment by leezen** [comment]
I see. Sorry for the confusion and we should probably document this better. It's not a bug that both exist -- this is by design. One method returns an object of the actual resource type based on the unique identifier while the other returns a lookup result based on some set of criteria. This functionality exists across all the SDKs (as described here: https://www.pulumi.com/docs/intro/concepts/programming-model/#resource-get). The lookup functions allow one to lookup resources in potentially other ways. As an example:

`aws.ec2.getInstance` allows lookup via a set of filters (and not necessarily id) https://www.pulumi.com/docs/reference/pkg/aws/ec2/getinstance/#using whereas https://www.pulumi.com/docs/reference/pkg/aws/ec2/instance/#look-up is intended to get back an instance purely based on ID.
