### ISSUE TITLE
Importing existing GCP service account violates pulumi id regex.

### ISSUE THREAD

**Issue by mvpmvh** [pulumi/pulumi-gcp#360]
I'm attempting to import an existing service account in GCP. The service account is created by default when enabling the Cloud Build api. The id of my default service account is `418715367700-compute`. Attempting to set that value in go returns the following error:

```
Diagnostics:
  gcp:serviceAccount:Account (cloud-build):
    error: gcp:serviceAccount/account:Account resource 'cloud-build' has a problem: "account_id" ("418715367700-compute") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
    error: Preview failed: one or more inputs failed to validate
```

**Comment by leezen** [comment]
That validation appears to come from upstream https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_google_service_account.go#L42 and claims to be copied from the official Google Cloud auto-generated client (which is corroborated by https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/create)

Are you certain that `418715367700-compute` isn't the name of the service account and it actually has some other ID? Otherwise, I don't think the Google API would've let you create this in the first place?

**Comment by mvpmvh** [comment]
```
= gcp:serviceAccount/account:Account: (import)
        [id=projects/my-project/serviceAccounts/service-account-id]
        [urn=urn:pulumi:stack::project::gcp:serviceAccount/account:Account::cloud-build]
      ~ accountId: "418715367700-compute" => "foo123"
```

The `pulumi up` details show the diff between the `accountID` in my code ("foo123"), and the `accountID` pulumi expects ("418715367700-compute"). When I attempt to change the value to the value shown in the diff, I get the above error.

**Comment by aryehb** [comment]
This appears to still be an issue.

#361 is marked as fixing this issue, and this issue was closed as a result, but I believe that is a mistake, as I commented there. #361 fixes #359, and this issue is unrelated and should be re-opened.  
@stack72 Can you confirm and re-open?

>Are you certain that 418715367700-compute isn't the name of the service account and it actually has some other ID? Otherwise, I don't think the Google API would've let you create this in the first place?

The ID for the default service account for Compute Engine is `{NUMERIC_PROJECT_ID}-compute`, and is auto-generated by GCP.

It appears the GCP Terraform provider has the [same issue](https://github.com/hashicorp/terraform-provider-google/issues/7443). There's a dedicated resource mentioned in a [comment](https://github.com/hashicorp/terraform-provider-google/issues/7443#issuecomment-704806839) on that issue for the default Compute Engine service account ([resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_default_service_account), [source](https://github.com/hashicorp/terraform-provider-google/blob/21c447bf4b721018eed51bf1b75c2f073136d004/google/data_source_google_compute_default_service_account.go)), which I presume doesn't have the regular restrictions.

Pulumi has a [dedicated function](https://www.pulumi.com/registry/packages/gcp/api-docs/compute/getdefaultserviceaccount/) for returning the default service account. However, I can't find a corresponding resource in the Pulumi documentation.

**Comment by mezhaka** [comment]
I use terraform and I get the same error:
```
 resource "google_service_account" "compute" {
   account_id   = "953934168937-compute@developer.gserviceaccount.com"
   display_name = "Compute Engine default service account"
 }
```
I see
```
╷
│ Error: "account_id" ("953934168937-compute@developer.gserviceaccount.com") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
│
│   with module.service-accounts.google_service_account.compute,
│   on modules/service-accounts/main.tf line 263, in resource "google_service_account" "compute":
│  263:    account_id   = "953934168937-compute@developer.gserviceaccount.com"
│
```

**Comment by aryehb** [comment]
@mezhaka Did you try using [`google_compute_default_service_account`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_default_service_account) instead?

**Comment by mezhaka** [comment]
> @mezhaka Did you try using [`google_compute_default_service_account`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_default_service_account) instead?

Oh! I did not know about that. It did help. Thank you!
