### ISSUE TITLE
Failing to delete a node pool should not leave the stack in "unknown" state

### ISSUE THREAD

**Issue by manast** [pulumi/pulumi-gcp#439]
This error has happened me several times, when doing a ```pulumi destroy``` for some reason deleting the node pool is slow and it seems that some token expires which leads to the following error:
![image](https://user-images.githubusercontent.com/95200/92510436-21decb80-f20c-11ea-9e8e-331bd52efafe.png)

I think it is acceptable to have this error even if it is not particularly elegant, however the problem comes if we try to do retry the destroy:
![image](https://user-images.githubusercontent.com/95200/92510534-4aff5c00-f20c-11ea-9f70-d40edd4967a5.png)

I know that now it is time to export the stack, remove pending operations and re-import, however this is usually implies opening a can of worms, specially if dependencies are involved, most of the time the only solution is just to remove the whole stack with --force.

**Comment by manast** [comment]
as a demonstration, in this case after removing the pending operation for deleting the node pool we arrive to this situation that as far as I know is hopeless:
![image](https://user-images.githubusercontent.com/95200/92510994-f90b0600-f20c-11ea-8dec-ce4baf70f67e.png)

**Comment by leezen** [comment]
If the resource is actually gone, but the state file does not match, you can remove the resource from state via `pulumi state delete`

**Comment by manast** [comment]
I do not think that is possible because other resources are depending on this resource, which in and by itself is strange.

**Comment by mikhailshilkov** [comment]
This issue is three years old and I'm pretty sure we have meaningfully changed the behavior of the CLI regarding pending operations. Given lack of comments since 2020, and the fact that the fix probably belongs in pulumi/pulumi and not the provider, I'll go ahead and close this issue as non-actionable.

If anyone still experiences a similar problem, please open a new issue with all the details, since I expect the actual symptoms/behavior are going to be different today.
