### ISSUE TITLE
Importing a gcp VPNTunnel fails

### ISSUE THREAD

**Issue by v0lk3r** [pulumi/pulumi-gcp#562]
Trying to import a gcp VPNTunnel fails because the `shared_secret` doesn't seem to be handled properly. The error occurs for the `pulumi import` command and when trying to import programmatically.

The described problem occurs with the latest pulumi 2.25.2 client/SDK as well as 3.0.0rc1 (and the corresponding python libraries)

## Expected behavior
The resource should be imported

## Current behavior
The following code snippet fails to import:
``` python
vpn_tunnel = gcp.compute.VPNTunnel(
    "vpn-tunnel",
    name="vpn-tunnel",
    shared_secret="redacted",
    target_vpn_gateway="redacted",
    opts=pulumi.ResourceOptions(
        import_="projects/<prj>/regions/<region>/vpnTunnels/vpn-tunnel",
    ),
)
```
This is the error:
```
warning: inputs to import do not match the existing resource; importing this resource will fail
    = gcp:compute/vPNTunnel:VPNTunnel: (import)
        [id=projects/<prj>/regions/<region>/vpnTunnels/vpn-tunnel]
        [urn=urn:pulumi:testing::network::gcp:compute/vPNTunnel:VPNTunnel::vpn-tunnel]
        [provider=urn:pulumi:testing::network::pulumi:providers:gcp::default_4_21_0::9400fa64-3729-3efb-bb74-7183febcae7b]
      + sharedSecret: "redacted"
```
I have double-checked that the sharedSecret is indeed correct. I tried the suggested workaround for similar import problems using the `ignore_changes` option, but that doesn't help. If I use the `ignore_changes` option I get this error:

```
Diagnostics:
  gcp:compute:VPNTunnel (vpn-tunnel):
    error: gcp:compute/vPNTunnel:VPNTunnel resource 'vpn-tunnel' has a problem: Required attribute is not set. Examine values at 'VPNTunnel.SharedSecret'.
    error: Preview failed: one or more inputs failed to validate
```

## Steps to reproduce

1. Create a VPN Gateway and Tunnel in GCP
2. Try importing them with `pulumi preview` and the above code snippet

## Context (Environment)
I am trying to migrate from an existing infrastructure created with terraform to pulumi.

**Comment by rquitales** [comment]
Hi @v0lk3r 

Thanks for reporting this, and apologies for the slow response. I believe this is no longer an issue with the latest Pulumi versions of CLI and SDKs. I've tested this out locally and no longer get any import issues related to the sharedSecret. There is a warning that occurs:
```
gcp:compute:VPNTunnel (tunnel1):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `gcp` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: gcp:compute/vPNTunnel:VPNTunnel resource 'tunnel1' has a problem: Missing required argument: The argument "shared_secret" is required, but no definition was found.. Examine values at 'VPNTunnel.SharedSecret'.


Do you want to perform this import? details
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:python-vpn::pu::pulumi:pulumi:Stack::pu-python-vpn]
    = gcp:compute/vPNTunnel:VPNTunnel: (import) 🔒
        [id=projects/<prj>/regions/us-central1/vpnTunnels/tunnel-1-credible-cat]
        [urn=urn:pulumi:python-vpn::pu::gcp:compute/vPNTunnel:VPNTunnel::tunnel1]
        [provider=urn:pulumi:python-vpn::pu::pulumi:providers:gcp::default_6_49_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        localTrafficSelectors: [
            [0]: "10.128.0.0/20"
        ]
        name                 : "tunnel-1-credible-cat"
        peerIp               : "15.0.0.120"
        region               : "us-central1"
```

Note that this is a warning and you will still be able to import the VPN tunnel regardless. This warning is likely due to the API server not returning a `shared_secret` field. Thus if you have `shared_secret` set in your Pulumi Python program, there would be drift since the state file will have this field as empty. The current Pulumi CLI will output a code snippet which you can use within your Python program to eliminate this drift. You should really be using this as VPNTunnels are immutable so any changes Pulumi detects would cause a replacement of the resource.

Will close this issue, but feel free to reopen if there are any more issue with import VPNTunnels.

**Comment by sy-bee** [comment]
@v0lk3r , have you managed to overcome this issue?

**Comment by sy-bee** [comment]
For anyone encountering this issue while trying to import via ResourceOptions (e.g. inside their Automations API project) - set the `shared_secret` to `""` (empty string) for import to succeed.
