### ISSUE TITLE
pulimi import of cloudsql instance gives an unknown error

### ISSUE THREAD

**Issue by willkessler** [pulumi/pulumi-gcp#591]
Hoping to import a cloudsql instance. Getting an error that I can't understand.

## Steps to reproduce

```
pulumi import  -d gcp:sql/databaseInstance:DatabaseInstance master <project-id>/<cloudsql_id>
```

produces

```
gcp:sql:DatabaseInstance (master):
    error: gcp:sql/databaseInstance:DatabaseInstance resource 'master' has a problem: AtLeastOne: "clone": one of `clone,settings` must be specified. Examine values at 'DatabaseInstance.Clone'.
    error: gcp:sql/databaseInstance:DatabaseInstance resource 'master' has a problem: AtLeastOne: "settings": one of `clone,settings` must be specified. Examine values at 'DatabaseInstance.Settings'.
    error: Preview failed: one or more inputs failed to validate
```

Expected: I'd expect typescript code for the instance
Actual: I get the error above. Wondering if this command can only be done with bulk import, and whether some additional parameters would need to be passed along via the bulk file?

**Comment by lukehoban** [comment]
This is similar to the issues tracked in https://github.com/pulumi/pulumi/issues/7160.  Like the others there, this happens because the requirement in this case is something that Pulumi does not know about, but is a restriction within GCP itself.  For now, you will likely need to modify the generated code to correctly specify the resource as require by GCP.  We will be exploring deeper fixes here in https://github.com/pulumi/pulumi/issues/7160.
