### ISSUE TITLE
Initialization issues on lb => neg => gateway

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi-gcp#664]
Hey guys,

I created a sample project for gcp serverless apps [here](https://github.com/s-dschro/gcp-serverless).

The data flow is as follows:
lb (dns-name, ssl-cert, etc.) => backend-service => network endpoint group => network endpoint => apigateway => cloudfunction

I used this article as a blueprint: [Medium](https://medium.com/swlh/google-api-gateway-and-load-balancer-cdn-9692b7a976df)

Whenever I do a fresh deployment on this infrastructure I am constantly getting a **502** on the lb (even if I wait multiple hours, so there is no init-time issue or something like that).
Whenever I do manually updating the backend-service in the gcp console (e.g. by updating its cloudcdn config), it seems something gets triggered/refreshed in the background, because then the lb is working immediately.

Have you encoutered this issue / race condition before? Do you know any workarounds? Do you think the issue is on pulumi-provider side or on gcp side?

Any help is appreciated.

**Comment by leezen** [comment]
Sorry that my suggestion wasn't helpful. If there's no difference between the two states after refresh, then I'm less sure about what's going on since that implies there's no configuration issue in terms of having the right configuration applied to the service. Is it possible there's some additional resource being created that's not modeled in your program?

**Comment by mikhailshilkov** [comment]
The link to repro doesn't work anymore, so I think issue isn't actionable for us. I apologise we haven't addressed it in a timely manner. If folks experience similar problems, please open a new issue and add your repro to it. Thank you!
