### ISSUE TITLE
Missing recaptcha resources

### ISSUE THREAD

**Issue by Sytten** [pulumi/pulumi-gcp#734]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The recaptcha resource was added in the terraform provider v4.4.0 (https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.4.0), but it is not present in pulumi despite it claiming to be at the provider version 4.8.0.
Unsure if it is a bug in the code generation or something else that needs to be done manually to add the resource.

**Comment by viveklak** [comment]
@jkodroff could you investigate why this is missing?

**Comment by jkodroff** [comment]
The resource appears to not be mapped in `resources.go` as it should be. Two things to do:

1. Add the resource (assuming we're not intentionally not mapping it, which is unlikely).
2. Verify that tfgen produced a message and we just missed it. (We're adding a flag that will fail the build for a missing mapping so that this can't be missed by a human.)

**Comment by jkodroff** [comment]
@Sytten First, thank you for taking the time to report the issue!

The resource is present in the latest version of the GCP provider, released yesterday: https://www.pulumi.com/registry/packages/gcp/api-docs/recaptcha/

**Comment by Sytten** [comment]
Thanks a lot!
