### ISSUE TITLE
bigquery reservation v1beta1 endpoint is going to be deprecated. Can we switch to their v1 endpoint?

### ISSUE THREAD

**Issue by panxuejian** [pulumi/pulumi-gcp#916]
### What happened?

See here for the deprecation:
https://cloud.google.com/bigquery/docs/reference/reservations/rpc/google.cloud.bigquery.reservation.v1beta1

If I understand it correctly, pulumi-gcp uses terraform under the hood. Terraform just switched to v1:https://github.com/hashicorp/terraform-provider-google/issues/12479

So can we update as well?

### Steps to reproduce

N/A

### Expected Behavior

Make sure the tool talks to bigquery reservation v1 endpoint.

### Actual Behavior

Current version talks to bigquery reservation v1beta1 endpoint. However it will be broken soon.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
`pulumi-gcp` uses `terraform-provider-google-beta` under the hood, so we will automatically pick up this change once it makes it into an upstream release. https://github.com/hashicorp/terraform-provider-google-beta/pull/4739 is the relevant change. I'll close this out since it will happen as part of the normal release process.
