### ISSUE TITLE
[TS] Boolean metadata annotation not allowed

### ISSUE THREAD

**Issue by nicaura** [pulumi/pulumi-gcp#957]
### What happened?

Trying to set `gcp.cloudrun.Service` annotation like so : 
```
...
metadata: {
  annotations: {
    "autoscaling.knative.dev/maxScale": "...",
    "run.googleapis.com/cloudsql-instances": "...",
    "run.googleapis.com/cpu-throttling": true
  },
},
```
But Typescript complains `Type 'boolean' is not assignable to type 'Input<string>'.ts(2322)`.
When trying to pass it as `string` we get the following error after a `pulumi up` : 
```
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value 1. Annotation run.googleapis.com/cpu-throttling must be a boolean",
        "field": "spec.template.metadata.annotations"
      }
    ]
  }
]
```

### Steps to reproduce

```
import * as gcp from "@pulumi/gcp";

new gcp.cloudrun.Service("default", {
  location: "us-central1",
  template: {
      spec: {
          containers: [{
              image: "gcr.io/cloudrun/hello",
          }],
      },
  },
  metadata: {
    annotations: {
      "run.googleapis.com/cpu-throttling": true
    },
  },
});
```

### Expected Behavior

Be able to pass `boolean` type to metadata annotation.

### Actual Behavior

Cannot pass `boolean` type to metadata annotation.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Thanks for the issue @nicaura! I've raised this with the team to be prioritized and added to our work stack. This odd because the [docs from google](https://cloud.google.com/run/docs/reference/rpc/google.cloud.run.v1#service) imply that annotations take string, string - and even point directly to [K8s docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) that explicitly say that both keys and values in annotations must be strings.

Might be worth noting that upstream the annotation field is [TypeMap](https://github.com/pulumi/terraform-provider-google-beta/blob/8b4421722d6a09dc4cb97b446cff6b5fb4dd0438/google-beta/resource_cloud_run_service.go#L60) which is [apparently](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#typemap) `map[string]any` (not `map[string]string`).

**Comment by mikhailshilkov** [comment]
I _think_ string-only values are by design here. FWIW the following code 

```ts
import * as gcp from "@pulumi/gcp";

new gcp.cloudrun.Service("default", {
  location: "us-central1",
  template: {
      spec: {
          containers: [{
              image: "gcr.io/cloudrun/hello",
          }],
      },
  },
  metadata: {
    annotations: {
      "run.googleapis.com/cpu-throttling": "true"
    },
  },
});
```

returns a different error now:

> Annotation 'run.googleapis.com/cpu-throttling' is not supported on resources of kind 'Service'. Supported kinds are: Revision

So maybe the original error is fixed? Are you still using this code to try again @nicaura?
