### ISSUE TITLE
When getting an existing cluster, there isn't a way to pull the kubeconfig

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-gcp#97]
In the current cluster object, we can use the `cluster` props: `certificateAuthority`, `name`, and `endpoint` to fill in the blanks in the kubeconfig file https://gist.github.com/b01eeecacccc3e284771463ed626af5e

we only do this right now in the object constructor, when we should actually have a `kubeconfig()` method on the object.

see community slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1550871454193500?thread_ts=1550862777.160400&cid=C84L4E3N1

related: https://github.com/pulumi/pulumi-aws/issues/478

**Comment by NinoFloris** [comment]
Is there some workaround besides manually templating the kubeconfig?

**Comment by lukehoban** [comment]
For now - you need to copy the boilerplate from one of the examples - like https://github.com/pulumi/examples/blob/master/gcp-ts-gke/cluster.ts#L27.

This issue is tracking putting that boilerplate behind a named function in the `@pulumi/gcp` package, but should not technically be a blocker for any scenarios.

**Comment by NinoFloris** [comment]
Thanks so much for the fast response!

**Comment by mikhailshilkov** [comment]
Closing as a dupe of #1064
