### ISSUE TITLE
Method compute.getSnapshot reports no error if snapshot doesn't exist

### ISSUE THREAD

**Issue by Narrayahodeir** [pulumi/pulumi-gcp#986]
### What happened?

I want to get the selflink of an existing compute snapshot so I use the method:

```
const mySnapshot = gcp.compute.getSnapshot({
  name: 'myapp-snapshot',
  project: gcpProjectId,
});
```

But if the name of the snapshot doesn't exist Pulumi proceeds. The selflink is being generated, though the snapshot name is invalid. I take the selflink output and use it to create a persistent disk. The persistent disk then become unusable.

### Expected Behavior

After executing `pulumi up` I await `Error 404: "The resource 'projects/myproject/global/snapshots/myapp-snapshot' was not found"` so that Pulumi is failing and doesn't proceed with the worklfow. 

### Steps to reproduce

Define the Output and a persistent Disk resource:

```
const mySnapshot = gcp.compute.getSnapshot({
  name: 'myapp-snapshot',
  project: gcpProjectId,
});

const mydisk = new gcp.compute.Disk('mydisk', {
  snapshot: mySnapshot.then(snap => snap.selfLink),
});
```

### Output of `pulumi about`

CLI          
Version      3.54.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.2
Arch     x86_64

This project is written in nodejs: executable='/bin/node' version='v16.19.0

### Additional context

If I test directly against the GCP API at https://cloud.google.com/compute/docs/reference/rest/v1/snapshots/get I get the expected behavior with an Error 404. 

And if I test with an invalid image instead of a snapshot as a Pulumi resource I also get Error 404 and Pulumi stops the workflow.

I use the latest pulumi/gcp version 6.49.0.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @Narrayahodeir thanks for reaching out.

I've just tried this out and can confirm that calling `gcp.compute.getSnapshot` with any arbitary name just returns an empty result: e.g.

```typescript
export const mySnapshot = gcp.compute. getSnapshot({
  name: "not-a-snapshot",
});
```

outputs:

```
mySnapshot: {}
```

However, this seems to be true across the board - for example the same behaviour exists for `getFunction`:

```typescript
export const myFunction = gcp.cloudfunctionsv2.getFunction({
  name: "not-a-function",
  location: "us-central1",
});
```

outputs:

```
myFunction: {}
```

The reason for this is historically to allow your program to continue and handle the empty case, otherwise the error will cause the whole deployment to fail. Ideally it would be good to surface these errors better, but this would require a much larger change across all providers and the core runtime.

I'm going to close this specific issue as by-design. There may be an existing issue in https://github.com/pulumi/pulumi which already captures this, otherwise this would need to be re-written as a more general case issue.
